; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
name = "Chelonian Access"
description = "Modern RFID Entry System - Shelled in Security"
default_envs = esp32c3

; Common settings for all environments
[env]
lib_deps =
    adafruit/Adafruit PN532
    https://github.com/holmser/JQ6500_Serial_ESP32
    plerup/EspSoftwareSerial
    adafruit/Adafruit NeoPixel
    me-no-dev/AsyncTCP
    me-no-dev/ESPAsyncWebServer

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.filesystem = littlefs

; Automatically upload LittleFS after firmware upload
; extra_scripts = pre:upload_littlefs.py

framework = arduino
monitor_speed = 115200
upload_protocol = esptool
debug_tool = esp-builtin
debug_init_break = tbreak setup
debug_server =
    $PLATFORMIO_CORE_DIR/packages/tool-openocd-esp32/bin/openocd
    -f $PLATFORMIO_CORE_DIR/packages/tool-openocd-esp32/share/openocd/scripts/board/esp32c3-builtin.cfg
; upload_port = /dev/ttyACM1  ; linux device
; monitor_port = /dev/ttyACM1 ; linux device
lib_ignore = 
    mocks
    SoftwareSerial ;Incompatible with ESP32, causes compilation error
build_flags =
    -D ESP32C3
    -D USINGMP3
    -DCORE_DEBUG_LEVEL=5
    -UCONFIG_LOG_DEFAULT_LEVEL    ; Undefine conflicting definition
    -UCONFIG_LOG_MAXIMUM_LEVEL    ; Undefine conflicting definition
    -DCONFIG_LOG_DEFAULT_LEVEL=5  ; Set default log level to INFO (0=None, 1=Error, 2=Warn, 3=Info, 4=Debug, 5=Verbose)
    -DCONFIG_LOG_MAXIMUM_LEVEL=5   ; Allow verbose logs to be compiled
    -DCONFIG_LOG_DYNAMIC_LEVEL_CONTROL=1 ; Enable dynamic log level control
    -D ARDUINO_USB_MODE=1          ; Enable USB hardware (if used).
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG=1 ; Direct console output to USB Serial/JTAG

test_ignore =
    test_native
    test_embedded
    test_native/*

; Test environment for native unit testing
[env:native]
platform = native
test_framework = unity
build_flags =
    -std=c++11
    -Wall
    -Wextra
    -D UNIT_TEST
    -D USINGMP3
    -I lib/mocks
    -I lib/test_helpers
    -lgcov
    --coverage             ; Enable coverage
    -ftest-coverage        ; Add test coverage
build_unflags = -Os        ; Disable optimization for accurate coverage
lib_deps =
    Unity
test_ignore =
    test_embedded
    test_native
test_filter = test_native/*
