name: chelonian_app
description: Chelonian Access Controller
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 2.2.1
  shared_preferences: ^2.2.0
  uuid: ^4.0.0
  flutter_beacon: ^0.5.1
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true